name: create env file

on:
  workflow_dispatch:

jobs:
  create-env-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
